// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbfUNlTREMeZE86bjSTqzu9TutzeCLsfs',
    appId: '1:509711775144:web:794fe0b76663fa75e0599d',
    messagingSenderId: '509711775144',
    projectId: 'datbannhahang',
    authDomain: 'datbannhahang.firebaseapp.com',
    storageBucket: 'datbannhahang.firebasestorage.app',
    measurementId: 'G-KL8SB0JK33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnIa0IuKjNkwm4nqfSD0E454AATj6pJGo',
    appId: '1:509711775144:android:9e182a0fd3311488e0599d',
    messagingSenderId: '509711775144',
    projectId: 'datbannhahang',
    storageBucket: 'datbannhahang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsdqcWJoM3_07bxx_vHWukm2SYe34k5xY',
    appId: '1:509711775144:ios:7412dd5fd084a4bde0599d',
    messagingSenderId: '509711775144',
    projectId: 'datbannhahang',
    storageBucket: 'datbannhahang.firebasestorage.app',
    iosBundleId: 'com.example.baitap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsdqcWJoM3_07bxx_vHWukm2SYe34k5xY',
    appId: '1:509711775144:ios:7412dd5fd084a4bde0599d',
    messagingSenderId: '509711775144',
    projectId: 'datbannhahang',
    storageBucket: 'datbannhahang.firebasestorage.app',
    iosBundleId: 'com.example.baitap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbfUNlTREMeZE86bjSTqzu9TutzeCLsfs',
    appId: '1:509711775144:web:3cbde5ecfab85adfe0599d',
    messagingSenderId: '509711775144',
    projectId: 'datbannhahang',
    authDomain: 'datbannhahang.firebaseapp.com',
    storageBucket: 'datbannhahang.firebasestorage.app',
    measurementId: 'G-6D3Y6D30EN',
  );

}